#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const input = path.resolve(process.cwd(), process.argv[2] || 'artifacts/extracted-full-runtime-css.css')
const output = path.resolve(process.cwd(), process.argv[3] || 'app/assets/css/extracted.css')

function stripVueScopedSelectors(css) {
  return css
    .replace(/\[data-v-[a-f0-9]+\]/gi, '')
    .replace(/\[data-v-[^\]]+\]/gi, '')
    .replace(/data-v-[a-f0-9]+="?"?/gi, '')
}

function removeObviousComments(css) {
  return css.replace(/\/\*(?![!*])[\s\S]*?\*\//g, '')
}

function normalizeWhitespace(css) {
  return css
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\s*([{}:;,>+~])\s*/g, '$1')
    .replace(/;}/g, '}')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function dedupeSimpleBlocks(css) {
  const preserved = []
  const protectedCss = css.replace(/@(keyframes|media|supports|font-face|page)[\s\S]*?\n?}\s*/gi, block => {
    const token = `___PROTECTED_BLOCK_${preserved.length}___`
    preserved.push(block)
    return token
  })

  const seen = new Set()
  const deduped = protectedCss.replace(/([^{}@]+)\{([^{}]*)\}/g, (match, selector, body) => {
    const cleanSelector = selector.trim().replace(/\s+/g, ' ')
    const cleanBody = body.trim().replace(/\s+/g, ' ')
    const key = `${cleanSelector}{${cleanBody}}`
    if (!cleanSelector || !cleanBody || seen.has(key)) return ''
    seen.add(key)
    return `${cleanSelector}{${cleanBody}}\n`
  })

  return deduped.replace(/___PROTECTED_BLOCK_(\d+)___/g, (_, index) => preserved[Number(index)] || '')
}

let css
try {
  css = await readFile(input, 'utf8')
} catch (error) {
  throw new Error(`Cannot read CSS input at ${input}. Run npm run extract first, or pass an input path. ${String(error)}`)
}

const cleaned = normalizeWhitespace(dedupeSimpleBlocks(removeObviousComments(stripVueScopedSelectors(css))))
const banner = `/* Cleaned CSS generated by scripts/clean-css.mjs. Review before production use. */\n`
await mkdir(path.dirname(output), { recursive: true })
await writeFile(output, `${banner}${cleaned}\n`, 'utf8')
console.log(JSON.stringify({ input, output, inputBytes: css.length, outputBytes: cleaned.length }, null, 2))
