#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const manifestPath = path.resolve(process.cwd(), process.argv[2] || 'artifacts/manifest.json')
const outputPath = path.resolve(process.cwd(), 'app/data/extracted-content.ts')

function uniqueBy(items, keyFn) {
  const seen = new Set()
  return items.filter(item => {
    const key = keyFn(item)
    if (!key || seen.has(key)) return false
    seen.add(key)
    return true
  })
}

let manifest
try {
  manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
} catch (error) {
  throw new Error(`Cannot read ${manifestPath}. Run npm run extract first. ${String(error)}`)
}

const navCandidates = uniqueBy(
  (manifest.anchors || [])
    .filter(anchor => anchor.text && anchor.text.length <= 36)
    .map(anchor => ({ label: anchor.text, href: anchor.href || '#' })),
  item => item.label
).slice(0, 40)

const images = uniqueBy(
  (manifest.images || [])
    .filter(image => image.src && !image.src.startsWith('data:'))
    .map(image => ({ src: image.src, alt: image.alt || '', width: image.width || 0, height: image.height || 0 })),
  item => item.src
).slice(0, 80)

const file = `// Generated by scripts/convert-to-nuxt.mjs. Review before committing.\nexport const extractedNavigation = ${JSON.stringify(navCandidates, null, 2)} as const\n\nexport const extractedImages = ${JSON.stringify(images, null, 2)} as const\n\nexport const extractedMeta = ${JSON.stringify({
  capturedAt: manifest.capturedAt,
  targetUrl: manifest.targetUrl,
  title: manifest.runtime?.title,
  classification: manifest.classification
}, null, 2)} as const\n`

await mkdir(path.dirname(outputPath), { recursive: true })
await writeFile(outputPath, file, 'utf8')
console.log(JSON.stringify({ outputPath, navItems: navCandidates.length, images: images.length }, null, 2))
